name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Branch principal do seu repositório

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Versão atualizada

      - name: Prepare deployment
        run: |
          mkdir -p build
          shopt -s extglob
          cp -r !(build|.git|.github) build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Versão atualizada
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build  # Diretório temporário onde os arquivos serão copiados
