name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Branch principal do repositório privado

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          external_repository: luciano-analytics/ds
          publish_branch: gh-pages  # Branch no repositório público onde a página será publicada
          publish_dir: /  # Diretório raiz onde os arquivos serão publicados
