name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Branch principal do seu repositório privado

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          external_repository: luciano-analytics/ds
          publish_branch: gh-pages  # Continuaremos usando o branch gh-pages para a publicação
          publish_dir: /             # Publicando diretamente da raiz do repositório
